# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-08 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBackSite',
            fields=[
                ('site_url', models.CharField(error_messages={'unique': 'site already existed'}, max_length=20, unique=True)),
                ('site_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_num', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('sec_code', models.CharField(max_length=4)),
                ('card_name', models.CharField(max_length=10, unique=True)),
                ('card_exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EarningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_site_cashback', models.FloatField()),
                ('credit_card_cashback', models.FloatField()),
                ('earing_num', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('card_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('card_num', models.CharField(max_length=30)),
                ('pin_num', models.CharField(max_length=10)),
                ('is_used', models.BooleanField()),
                ('remain_value', models.FloatField(default=models.FloatField())),
            ],
        ),
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_inner_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('order_name', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('order_status', models.IntegerField(choices=[(0, 'ordered'), (1, 'shipped'), (2, 'canceled'), (3, 'delivered'), (4, 'picked')], default=0)),
                ('merchandiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.Merchandiser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20)),
                ('item_price', models.FloatField()),
                ('carrier', models.IntegerField(choices=[(0, 'Ups'), (1, 'Fedex'), (2, 'USPS'), (3, 'other'), (9, 'undefined')], default=9)),
                ('tracking_num', models.CharField(max_length=20)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.CreditCard')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.EarningDetail')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='giftcard',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.Merchandiser'),
        ),
        migrations.AddField(
            model_name='earningdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.Order'),
        ),
    ]
