# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_inner_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
