# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0002_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addr_name',
            field=models.CharField(max_length=20),
        ),
    ]
