# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0002_auto_20170908_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiser',
            name='url',
            field=models.CharField(default='undefined', max_length=20),
            preserve_default=False,
        ),
    ]
