# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0003_merchandiser_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='tracking_num',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
