# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0004_auto_20170915_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
