# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0005_auto_20170915_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earningdetail',
            old_name='order_id',
            new_name='order',
        ),
    ]
