# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0006_auto_20170915_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_inner_id',
            new_name='order_id',
        ),
    ]
