# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0007_auto_20170915_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdetail',
            name='cashback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PurchaseRecording.CashBackSite'),
        ),
    ]
