# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0007_auto_20170909_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_exp_date',
            field=models.DateField(),
        ),
    ]
