# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0008_auto_20170909_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdetail',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='earningdetail',
            name='other_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='earningdetail',
            name='cashback_site_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='earningdetail',
            name='credit_card_cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='earningdetail',
            name='earing_num',
            field=models.FloatField(default=0),
        ),
    ]
