# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0008_earningdetail_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacksite',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='reward',
            field=models.FloatField(default=0.0),
        ),
    ]
