# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0010_auto_20170915_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_date',
            field=models.DateField(default=datetime.date(2017, 9, 15)),
        ),
    ]
