# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRecording', '0011_auto_20170915_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
